---
# These tasks install Apache HTTPD

- name: Install Apache HTTPD from Red Hat repo
  yum:
    name=httpd
    state=latest

- name: Start firewalld
  service:
    name=firewalld
    state=started
    enabled=yes

- name: insert firewalld rule for http
  firewalld:
    port={{ httpd_port }}/tcp
    permanent=true
    state=enabled
    immediate=yes

- name: Restart nginx service
  service:
    name=httpd
    state=started
    enabled=yes
