---
# These tasks install PHP with MySQL modules.

- name: Install PHP with MySQL modules
  yum:
    name={{ item }}
    state=latest
  with_items:
   - php
   - php-mysql

- name: Restart HTTPD service
  service:
    name=httpd
    state=restarted
    enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name=httpd_can_network_connect_db
    state=true
    persistent=yes
