---
# These tasks install php and mysql modules.

- name: Install httpd and php
  yum:
    name={{ item }}
    state=latest
  with_items:
   - php
   - php-mysql

- name: http service state
  service:
    name=httpd
    state=restarted
    enabled=yes

- name: Configure SELinux to allow httpd to connect to remote database
  seboolean:
    name=httpd_can_network_connect_db
    state=true
    persistent=yes
