---
# This playbook will install MariaDB client

- name: Install MariaDB package
  yum:
    name=mariadb
    state=latest

- name: Configure SELinux to start mysql on any port
  seboolean:
    name=mysql_connect_any
    state=true
    persistent=yes
